services:
  cloudflaretunnel-demo:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xtermjs-demo:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
